export const FEED_GET_ALL_REQUEST = "FEED_GET_ALL_REQUEST";
export const FEED_GET_ALL_SUCCESS = "FEED_GET_ALL_SUCCESS";
export const FEED_GET_ALL_FAILURE = "FEED_GET_ALL_FAILURE";

export const FEED_GET_REQUEST = "FEED_GET_REQUEST";
export const FEED_GET_SUCCESS = "FEED_GET_SUCCESS";
export const FEED_GET_FAILURE = "FEED_GET_FAILURE";

export const FEED_CREATE_REQUEST = "FEED_CREATE_REQUEST";
export const FEED_CREATE_SUCCESS = "FEED_CREATE_SUCCESS";
export const FEED_CREATE_FAILURE = "FEED_CREATE_FAILURE";
