export const MARKETPLACE_GET_ALL_REQUEST = 'MARKETPLACE_GET_ALL_REQUEST';
export const MARKETPLACE_GET_ALL_SUCCESS = 'MARKETPLACE_GET_ALL_SUCCESS';
export const MARKETPLACE_GET_ALL_FAILURE = 'MARKETPLACE_GET_ALL_FAILURE';

export const MARKETPLACE_GET_REQUEST = 'MARKETPLACE_GET_REQUEST';
export const MARKETPLACE_GET_SUCCESS = 'MARKETPLACE_GET_SUCCESS';
export const MARKETPLACE_GET_FAILURE = 'MARKETPLACE_GET_FAILURE';

export const MARKETPLACE_CREATE_REQUEST = 'MARKETPLACE_CREATE_REQUEST';
export const MARKETPLACE_CREATE_SUCCESS = 'MARKETPLACE_CREATE_SUCCESS';
export const MARKETPLACE_CREATE_FAILURE = 'MARKETPLACE_CREATE_FAILURE';

export const MARKETPLACE_DELETE_REQUEST = 'MARKETPLACE_DELETE_REQUEST';
export const MARKETPLACE_DELETE_SUCCESS = 'MARKETPLACE_DELETE_SUCCESS';
export const MARKETPLACE_DELETE_FAILURE = 'MARKETPLACE_DELETE_FAILURE';
