export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_GET_PROFILE_REQUEST = "USER_GET_PROFILE_REQUEST";
export const USER_GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS";
export const USER_GET_PROFILE_FAILURE = "USER_GET_PROFILE_FAILURE";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAILURE = "USER_UPDATE_PROFILE_FAILURE";

export const USER_SELECT_PICTURE = "USER_SELECT_PICTURE";

export const USER_GET_USERPLANT_REQUEST = "USER_GET_USERPLANT_REQUEST";
export const USER_GET_USERPLANT_SUCCESS = "USER_GET_USERPLANT_SUCCESS";
export const USER_GET_USERPLANT_FAILURE = "USER_GET_USERPLANT_FAILURE";

export const USER_GET_ALL_USERPLANT_LOG_REQUEST = "USER_GET_ALL_USERPLANT_LOG_REQUEST";
export const USER_GET_ALL_USERPLANT_LOG_SUCCESS = "USER_GET_ALL_USERPLANT_LOG_SUCCESS";
export const USER_GET_ALL_USERPLANT_LOG_FAILURE = "USER_GET_ALL_USERPLANT_LOG_FAILURE";